version: '3'

services:
  influxdb:
    image: influxdb:1.7.10
    environment:
      - INFLUXDB_DB=telegraf
  nginx:
    image: nginx:1.17.9-alpine
    restart: always
    volumes:
      - ./conf/nginx_status.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '8888:80'
  telegraf:
    image: telegraf:1.13.4-alpine
    depends_on:
      - nginx
      - influxdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  grafana:
    image: grafana/grafana:6.6.2
    depends_on:
      - influxdb

