# API version
version: 1

# global configuration
config:
  host:
  port: 9999
  template: tmpl/lazydash.htm
  name: Lazy Dashboard (beta)
  page-size: 20
  database:
    driver: sqlite3
    host: .
    username:
    password: 
    database: demo.sql

# SQL query specification
spec:
  demo:
    table: player
    field:
      - column: name
      - column: age
  view:
    table: player
    field:
      - column: name
      - column: age
